#!/bin/bash
# Arch upgradeable packages

E_OK=0
E_WARNING=1
E_CRITICAL=2
E_UNKNOWN=3

warn=8
crit=15

if [[ -e /etc/os-release ]]
then
  . /etc/os-release
  distribution="${ID}"
fi

if [ "${distribution}" = "arch" ] || [ "${distribution}" = "artix" ] || [ "${distribution}" = "manjaro" ]
then

  PACMAN=$(command -v pacman)

  list=$(${PACMAN} --sync --sysupgrade --print 2> /dev/null)
  count=0

  if [ ! -z "${list}" ]
  then
    count=$(echo "${list}" | wc -l)
  fi

  if [[ "${count}" -gt 0 ]] && [[ "${count}" -lt "${warn}"  ]]
  then
    exit_code="${E_WARNING}"
    exit_msg="WARNING "
  elif [[ "${count}" -gt "${crit}"  ]]
  then
    exit_code="${E_CRITICAL}"
    exit_msg="CRITICAL "
  else
    exit_code="${E_OK}"
    exit_msg="OK "
  fi

  echo -e "${exit_msg} ${count} packages available for upgrade\n"

  for pkg in ${list}
  do
    echo -n "  "
    echo ${pkg} | sed -e 's#.*/##g' -e 's%(.*).pkg.*$%1%'
  done

else
  echo "wrong distribution."
  exit_code="${E_UNKNOWN}"
fi

exit ${exit_code}
